feat: :sparkles: test coding style error

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -10,55 +10,65 @@ on:
 
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-PAR-2-2-chocolatine-lou.onezime.git"
-  EXECUTABLES: "choco"
+  EXECUTABLES: "fizzbuzz"
   ARGUMENTS: "10, 15"
 
 jobs:
-  # check_coding_style:
-  #   name: "checks for coding style errors"
-  #   runs-on: ubuntu latest
-  #   container: ghcr.io/epitech/coding-style-checker:latest
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - id: check_coding_style
-  #       run: |
-  #         make fclean
-  #         BANANA = $(check.sh $(pwd) $(pwd))
+  check_coding_style:
+    name: "checks for coding style errors"
+    runs-on: ubuntu latest
+    container: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - uses: actions/checkout@v3
+      - id: check_coding_style
+        run: |
+          make fclean
+          BANANA = $(check.sh $(pwd) $(pwd))
+          for ERRORS in $BANANA; do
+            array=(`echo $ERRORS | sed 's/:/\n/g'`)
+            echo "::error file=${array[1]#./},title=${array[3]#./} coding style error: ${array[2]#./}::${array[4]#./}"
+          done
+          if [[ -n $BANANA ]]
+          then
+            exit 1
+          else
+            echo No coding style errors detected
+          fi
 
-  # check_program_compilation:
-  #   # needs: [check_coding_style]
-  #   name: "verifies that each file specified in the EXECUTABLES environment variable exists and is executable"
-  #   runs-on: ubuntu-latest
-  #   container: epitechcontent/epitest-docker:latest
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - id: check_program_compilation
-  #       run: make
-  #       timeout-minutes: 2
-  #     - run: make clean
-  #     - run: |
-  #         OIFS=$IFS
-  #         IFS=','
-  #         for x in $EXECUTABLES
-  #           do
-  #             ./$x $ARGUMENTS
-  #           done
-  #         IFS=$OIFS
+  check_program_compilation:
+    needs: [check_coding_style]
+    name: "verifies that each file specified in the EXECUTABLES environment variable exists and is executable"
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker:latest
+    steps:
+      - uses: actions/checkout@v3
+      - id: check_program_compilation
+        run: make
+        timeout-minutes: 2
+      - run: make clean
+      - run: |
+          OIFS=$IFS
+          IFS=','
+          for x in $EXECUTABLES
+            do
+              ./$x $ARGUMENTS
+            done
+          IFS=$OIFS
 
-  # run_tests:
-  #   needs: [check_program_compilation]
-  #   name: "runs tests because that's what heroes do"
-  #   runs-on: ubuntu-latest
-  #   container:
-  #     image: epitechcontent/epitest-docker:latest
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - id: run_tests
-  #       run: make tests_run
-  #       timeout-minutes: 2
+  run_tests:
+    needs: [check_program_compilation]
+    name: "runs tests because that's what heroes do"
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - uses: actions/checkout@v3
+      - id: run_tests
+        run: make tests_run
+        timeout-minutes: 2
 
   push_to_mirror:
-    # needs: [run_tests]
+    needs: [run_tests]
     if: ${{ github.event_name == 'push' }}
     name: "pushes all files to mirror specified"
     runs-on: ubuntu-latest
