feat: :zap: test other jobs

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -14,29 +14,29 @@ env:
   ARGUMENTS: "10, 15"
 
 jobs:
-  check_coding_style:
-    name: "checks for coding style errors"
-    runs-on: ubuntu latest
-    container: ghcr.io/epitech/coding-style-checker:latest
-    steps:
-      - uses: actions/checkout@v3
-      - id: check_coding_style
-        run: |
-          make fclean
-          BANANA = $(check.sh $(pwd) $(pwd))
-          for ERRORS in $BANANA; do
-            array=(`echo $ERRORS | sed 's/:/\n/g'`)
-            echo "::error file=${array[1]#./},title=${array[3]#./} coding style error: ${array[2]#./}::${array[4]#./}"
-          done
-          if [[ -n $BANANA ]]
-          then
-            exit 1
-          else
-            echo No coding style errors detected
-          fi
+  # check_coding_style:
+  #   name: "checks for coding style errors"
+  #   runs-on: ubuntu latest
+  #   container: ghcr.io/epitech/coding-style-checker:latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - id: check_coding_style
+  #       run: |
+  #         make fclean
+  #         BANANA = $(check.sh $(pwd) $(pwd))
+  #         for ERRORS in $BANANA; do
+  #           array=(`echo $ERRORS | sed 's/:/\n/g'`)
+  #           echo "::error file=${array[1]#./},title=${array[3]#./} coding style error: ${array[2]#./}::${array[4]#./}"
+  #         done
+  #         if [[ -n $BANANA ]]
+  #         then
+  #           exit 1
+  #         else
+  #           echo No coding style errors detected
+  #         fi
 
   check_program_compilation:
-    needs: [check_coding_style]
+    # needs: [check_coding_style]
     name: "verifies that each file specified in the EXECUTABLES environment variable exists and is executable"
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker:latest
